### ISSUE TITLE
Include resources based on 'include' query parameter (or lambda)

### ISSUE THREAD

**Issue by cmeeren** [scott-mcdonald/JsonApiFramework#48] opened 2018-03-16 20:46 UTC
I can't find a way to determine whether to include `included` resources. Relationships have a predicate I can use to determine if they're included in the JSON, but `included` resources do not seem to have this feature.

Ideally I would like JsonApiFramework to support the `include` query parameter, which can be used to specify which resources to include.

**Comment by scott-mcdonald** [comment] 2018-03-18 16:22
JsonApiFramework was intended to be a framework to create or integrate into higher level frameworks like WebApi for example that does support query parameters. In other words JsonApiFramework would be used as the implementation at a higher level framework for the "include" implementation.

But you are right, I do support predicates as lambdas for relationships to support the concept of HATEOAS on whether relationships are included or not. It wouldn't be that hard to add something similar to the "includes" part of document building to determine if the included resource is actually included or not. Do you think this would be valuable? If so, this is fairly trivial and I would be willing to add...

**Comment by cmeeren** [comment] 2018-03-18 16:40
I certainly need it if I end up using JsonApiFramework, but due to #47 I might end up using something simpler instead such as https://github.com/codecutout/JsonApiSerializer, otherwise I'll have to manually include all resources and nested resources, and for large-ish object graphs that seems to be a real pain.

**Comment by scott-mcdonald** [comment] 2018-03-19 22:30
Understood, definitely use the right tool for the right job. I do think adding an optional lambda for an include will bring some value so thanks for that idea. I think another enhancement is to pass a list of included relationship names in the Included() method and only included related resources being included under the respective relationship are actually included. That way a higher level framework like Web API can split the "include" query parameter on the ',' character and pass a collection of relationship names to the fluent-style building of a json:api document...

**Comment by scott-mcdonald** [comment] 2018-03-20 10:20
Going to close this issue as it generated enhancements #50 and #51.

**Closed by scott-mcdonald** 2018-03-20 10:20 UTC
